/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.customerRole;

import ui.marketingRole.*;
import userbusiness.UserLogin;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;
import salesmodel.CustomerManagement.CustomerProfile;
import salesmodel.Data.Data;
import salesmodel.utils.DataUtil;
import ui.UserLoginJPanel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import salesmodel.MarketModel.Channel;
import salesmodel.OrderManagement.Order;
import salesmodel.Personnel.Person;
import salesmodel.ProductManagement.Product;
import salesmodel.ProductManagement.SolutionBundleAssignment;
import salesmodel.ProductManagement.SolutionItem;
import salesmodel.ProductManagement.SolutionOffer;
import ui.UiControl;
import userbusiness.Account;

/**
 *
 * @author faye
 */
public class CustomerAccountScene extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private JFrame jf;
    private Data data;
    private Account account; 
    private CustomerProfile cp; 
    private ArrayList<String> characters;

    /**
     * Creates new form MarketingDashboard_new
     */
    public CustomerAccountScene(JFrame jf, Data data, Account account) {
        setBackground(new Color(0, 128, 128));
        this.jf = jf;
        this.data = data;
        this.account = account; 
        this.cp = data.getBusiness().cd.findCustomer(account.getPerson().getPersonId()); 
        characters = new ArrayList<String>();
        for(String c : cp.getcharacters()){
            this.characters.add(c);
        }
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        top_search_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        logout_btn = new javax.swing.JButton();
        my_account_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cart_btn = new javax.swing.JButton();
        order_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        char_table = new javax.swing.JTable();
        remove_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chart_textfiled = new javax.swing.JTextField();
        add_chara_btn = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        setMaximumSize(new java.awt.Dimension(680, 800));
        setPreferredSize(new java.awt.Dimension(664, 800));
        setSize(new java.awt.Dimension(680, 800));

        top_search_panel.setBackground(new java.awt.Color(0, 0, 0));
        top_search_panel.setMaximumSize(new java.awt.Dimension(800, 800));
        top_search_panel.setPreferredSize(new java.awt.Dimension(680, 74));
        top_search_panel.setSize(new java.awt.Dimension(680, 74));

        jLabel1.setBackground(new java.awt.Color(255, 203, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 163, 188));
        jLabel1.setText("Hello, "+this.account.getPerson().getName().split(" ")[0]);

        label1.setText("label1");

        logout_btn.setBackground(new java.awt.Color(204, 204, 204));
        logout_btn.setText("Log out");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        my_account_btn.setBackground(new java.awt.Color(204, 204, 204));
        my_account_btn.setText("My Account");

        javax.swing.GroupLayout top_search_panelLayout = new javax.swing.GroupLayout(top_search_panel);
        top_search_panel.setLayout(top_search_panelLayout);
        top_search_panelLayout.setHorizontalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(my_account_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        top_search_panelLayout.setVerticalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_search_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_btn)
                    .addComponent(my_account_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(236, 234, 234));

        cart_btn.setText("My Cart");
        cart_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_btnMouseClicked(evt);
            }
        });

        order_btn.setText("My Orders");
        order_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                order_btnMouseClicked(evt);
            }
        });

        home_btn.setText("Home");
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cart_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(order_btn)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cart_btn)
                    .addComponent(order_btn)
                    .addComponent(home_btn)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Copy Right 2020 Sales.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setText("Name:");

        name_textfield.setText(this.cp.getName());
        name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textfieldActionPerformed(evt);
            }
        });

        DefaultTableModel dtm = new DefaultTableModel(0, 0);

        String[] header = new String[]{""};
        dtm.setColumnIdentifiers(header);

        for(String c : this.characters){
            String[] arr = new String[1];
            arr[0] = c;
            dtm.addRow(arr);
        }
        char_table.setModel(dtm);
        char_table.getTableHeader().setUI(null);
        jScrollPane2.setViewportView(char_table);

        remove_btn.setText("Remove");
        remove_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remove_btnMouseClicked(evt);
            }
        });
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("My characteristics ");

        chart_textfiled.setText(" ");
        chart_textfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chart_textfiledActionPerformed(evt);
            }
        });

        add_chara_btn.setText("+");
        add_chara_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_chara_btnMouseClicked(evt);
            }
        });
        add_chara_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_chara_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(update_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75)
                                .addComponent(chart_textfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add_chara_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(remove_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chart_textfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_chara_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remove_btn)
                .addGap(19, 19, 19)
                .addComponent(update_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        UserLoginJPanel loginUI = new UserLoginJPanel(jf, data);
        UiControl.logout(this.jf, loginUI);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void home_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CustomerDashboard dashboard = new CustomerDashboard(this.jf, this.data, this.account);
        UiControl.dashboard(this.jf, dashboard); 
    }//GEN-LAST:event_home_btnMouseClicked

    private void order_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        OrderHistoryScene order = new OrderHistoryScene(this.jf, this.data, this.account);
        UiControl.viewCustomerOrder(this.jf, order); 
    }//GEN-LAST:event_order_btnMouseClicked

    private void cart_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CustomerCartScene cart = new CustomerCartScene(this.jf, this.data, this.account);
        UiControl.viewCustomerCart(this.jf, cart);
    }//GEN-LAST:event_cart_btnMouseClicked

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_btnActionPerformed

    private void name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textfieldActionPerformed

    private void add_chara_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_chara_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_chara_btnActionPerformed

    private void chart_textfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chart_textfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chart_textfiledActionPerformed

    private void add_chara_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_chara_btnMouseClicked
        // TODO add your handling code here:
        if(!this.chart_textfiled.getText().isBlank() && !this.characters.contains(this.chart_textfiled.getText().trim())){
            this.characters.add(this.chart_textfiled.getText().trim());
            DefaultTableModel dtm = (DefaultTableModel) this.char_table.getModel();
            String[] items = new String[1];
            dtm.addRow(new String[]{this.chart_textfiled.getText().trim()}); 
            dtm.fireTableDataChanged(); 
            this.chart_textfiled.setText("");
        }
    }//GEN-LAST:event_add_chara_btnMouseClicked

    private void remove_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove_btnMouseClicked
        // TODO add your handling code here:
        int selected_row = this.char_table.getSelectedRow();
        if (selected_row >= 0) { 
            this.characters.remove(selected_row);
            DefaultTableModel dtm = (DefaultTableModel) this.char_table.getModel(); 
            dtm.removeRow(selected_row);
            dtm.fireTableDataChanged(); 
        }
    }//GEN-LAST:event_remove_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        // TODO add your handling code here:
        String error = "";
        if(this.name_textfield.getText().isBlank()){
            error += "Name cannot be empty!\n";
        }
        if(this.characters.size()<1){
            error += "You need to have at least one charactertic";
        }
        if(error.isEmpty()){
            DataUtil.updateCustomerProfile(this.name_textfield.getText(), this.characters, this.cp);
            cleanPanel();
            CustomerAccountScene account = new CustomerAccountScene(this.jf, this.data, this.account);
            UiControl.viewAccount(this.jf, account);
            JOptionPane.showMessageDialog(this.jf, "Succeed");
        }
        else{
            JOptionPane.showMessageDialog(this.jf, error);
        }
    }//GEN-LAST:event_update_btnMouseClicked

    private void cleanPanel(){ 
        this.setVisible(false);
        this.removeAll();
        this.jf.remove(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_chara_btn;
    private javax.swing.JButton cart_btn;
    private javax.swing.JTable char_table;
    private javax.swing.JTextField chart_textfiled;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton my_account_btn;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JButton order_btn;
    private javax.swing.JButton remove_btn;
    private javax.swing.JPanel top_search_panel;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
