/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.customerRole;

import ui.marketingRole.*;
import userbusiness.UserLogin;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;
import salesmodel.CustomerManagement.CustomerProfile;
import salesmodel.Data.Data;
import salesmodel.utils.DataUtil;
import ui.UserLoginJPanel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import salesmodel.MarketModel.Channel;
import salesmodel.MarketModel.MarketChannelAssignment;
import salesmodel.OrderManagement.Order;
import salesmodel.Personnel.Person;
import salesmodel.ProductManagement.SolutionBundleAssignment;
import ui.UiControl;
import userbusiness.Account;

/**
 *
 * @author faye
 */
public class CustomerDashboard extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private JFrame jf;
    private Data data;
    private Account account;
    private CustomerProfile cp;
    private ArrayList<SolutionBundleAssignment> sa_list;
    private ArrayList<String> channels;
    private String channel_ads;

    /**
     * Creates new form MarketingDashboard_new
     */
    public CustomerDashboard(JFrame jf, Data data, Account account) {
        setBackground(new Color(0, 128, 128));
        this.jf = jf;
        this.data = data;
        this.account = account; 
        this.cp = data.getBusiness().cd.findCustomer(account.getPerson().getPersonId());
        this.channels = new ArrayList<String>();
        for(Channel channel : this.data.getBusiness().channel_list.getChannels()){
            this.channels.add(channel.getType()); 
        } 
         
        this.sa_list = DataUtil.getMarketChannelBundleAssignments(this.data, this.cp, this.data.getBusiness().channel_list.getChannels().get(0).getType());
        channel_ads = this.data.getBusiness().market_list.findMostMatchMarket(cp.getcharacters()).findAssignment(this.data.getBusiness().channel_list.getChannels().get(0)).getAds();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        top_search_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        my_account_btn = new javax.swing.JButton();
        channel_select_btn = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cart_btn = new javax.swing.JButton();
        order_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ads_table = new javax.swing.JTable();
        detail_btn = new javax.swing.JButton();
        ads_title = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        setMaximumSize(new java.awt.Dimension(680, 800));
        setPreferredSize(new java.awt.Dimension(664, 800));
        setSize(new java.awt.Dimension(680, 800));

        top_search_panel.setBackground(new java.awt.Color(0, 0, 0));
        top_search_panel.setMaximumSize(new java.awt.Dimension(800, 800));
        top_search_panel.setPreferredSize(new java.awt.Dimension(680, 74));
        top_search_panel.setSize(new java.awt.Dimension(680, 74));

        jLabel1.setBackground(new java.awt.Color(255, 203, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 163, 188));
        jLabel1.setText("Hello, "+this.account.getPerson().getName().split(" ")[0]);

        label1.setText("label1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Channel");

        logout_btn.setBackground(new java.awt.Color(204, 204, 204));
        logout_btn.setText("Log out");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        my_account_btn.setBackground(new java.awt.Color(204, 204, 204));
        my_account_btn.setText("My Account");
        my_account_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                my_account_btnMouseClicked(evt);
            }
        });

        String[] c_arr = new String[this.channels.size()];
        for(int i=0;i<this.channels.size();i++){
            c_arr[i] = this.channels.get(i);
        }
        channel_select_btn.setModel(new DefaultComboBoxModel<>(c_arr));
        channel_select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel_select_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout top_search_panelLayout = new javax.swing.GroupLayout(top_search_panel);
        top_search_panel.setLayout(top_search_panelLayout);
        top_search_panelLayout.setHorizontalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(channel_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(my_account_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        top_search_panelLayout.setVerticalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_search_panelLayout.createSequentialGroup()
                        .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(channel_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_btn)
                        .addComponent(my_account_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(236, 234, 234));

        cart_btn.setText("My Cart");
        cart_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_btnMouseClicked(evt);
            }
        });

        order_btn.setText("My Orders");
        order_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                order_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cart_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(order_btn)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cart_btn)
                    .addComponent(order_btn)))
        );

        DefaultTableModel dtm = new DefaultTableModel(0, 0);

        String[] header = new String[]{"Ads"};
        dtm.setColumnIdentifiers(header);

        for(SolutionBundleAssignment sa : this.sa_list){
            String[] arr = new String[1];
            arr[0] = sa.getBundle().getAds();
            dtm.addRow(arr);
        }
        Ads_table.setModel(dtm);
        Ads_table.getTableHeader().setUI(null);
        jScrollPane1.setViewportView(Ads_table);

        detail_btn.setText("View Details");
        detail_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detail_btnMouseClicked(evt);
            }
        });

        ads_title.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        ads_title.setText(this.channel_ads);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Copy Right 2020 Sales.com");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(detail_btn)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ads_title, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(ads_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detail_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        UserLoginJPanel loginUI = new UserLoginJPanel(jf, data);
        UiControl.logout(this.jf, loginUI);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void channel_select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel_select_btnActionPerformed
        // TODO add your handling code here: 
        String channel = String.valueOf(this.channel_select_btn.getSelectedItem());
        this.sa_list = DataUtil.getMarketChannelBundleAssignments(this.data, this.cp, channel);
        DefaultTableModel dtm = (DefaultTableModel) this.Ads_table.getModel();
        dtm.setRowCount(0);
        for(SolutionBundleAssignment sa : this.sa_list){
            String[] arr = new String[1];
            arr[0] = sa.getBundle().getAds();
            dtm.addRow(arr);
        }
        dtm.fireTableDataChanged(); 
        
        MarketChannelAssignment ma = this.data.getBusiness().market_list.findMostMatchMarket(cp.getcharacters()).findAssignment(this.data.getBusiness().channel_list.findChannel(channel));
        if(ma!=null){
           
            this.ads_title.setText(ma.getAds());
        }
        else {
            this.ads_title.setText("");
        }
        
    }//GEN-LAST:event_channel_select_btnActionPerformed

    private void detail_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detail_btnMouseClicked
        // TODO add your handling code here:
        int selected_row = this.Ads_table.getSelectedRow();
        if (selected_row >= 0) {
            cleanPanel();
            SolutionBundleAssignment sa = this.sa_list.get(selected_row);
            BundleDetailScene bs = new BundleDetailScene(this.jf, this.data, this.account, sa);
            UiControl.viewBundleDeatail(this.jf, bs);
        }
    }//GEN-LAST:event_detail_btnMouseClicked

    private void order_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_btnMouseClicked
        cleanPanel();
        OrderHistoryScene order = new OrderHistoryScene(this.jf, this.data, this.account);
        UiControl.viewCustomerOrder(this.jf, order);  
    }//GEN-LAST:event_order_btnMouseClicked

    private void cart_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CustomerCartScene cart = new CustomerCartScene(this.jf, this.data, this.account);
        UiControl.viewCustomerCart(this.jf, cart);
    }//GEN-LAST:event_cart_btnMouseClicked

    private void my_account_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_my_account_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CustomerAccountScene account = new CustomerAccountScene(this.jf, this.data, this.account);
        UiControl.viewAccount(this.jf, account);
    }//GEN-LAST:event_my_account_btnMouseClicked

    private void cleanPanel(){ 
        this.setVisible(false);
        this.removeAll();
        this.jf.remove(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ads_table;
    private javax.swing.JLabel ads_title;
    private javax.swing.JButton cart_btn;
    private javax.swing.JComboBox<String> channel_select_btn;
    private javax.swing.JButton detail_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton my_account_btn;
    private javax.swing.JButton order_btn;
    private javax.swing.JPanel top_search_panel;
    // End of variables declaration//GEN-END:variables
}
