/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.marketingRole;

import userbusiness.UserLogin;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;
import salesmodel.Data.Data;
import salesmodel.utils.DataUtil;
import salesmodel.utils.Util;
import ui.UserLoginJPanel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import salesmodel.OrderManagement.Order;
import salesmodel.OrderManagement.OrderItem;
import salesmodel.Personnel.EmployeeProfile;
import salesmodel.ProductManagement.Product;
import salesmodel.SupplierManagement.Supplier;
import ui.UiControl;
import userbusiness.Account;

/**
 *
 * @author faye
 */
public class CreateOfferScene extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtUser;
    private JFrame jf;
    private Data data;
    private Account account;
    private JLabel username_label;
    private JLabel serve_customer_label;
    private JLabel activity_label; 
     

    /**
     * Creates new form MarketingDashboard_new
     */
    public CreateOfferScene(JFrame jf, Data data, Account account) {
        setBackground(new Color(0, 128, 128));
        this.jf = jf;
        this.data = data;
        this.account = account; 
        initComponents();
        updateSupplierDrg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        top_search_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_search_input = new java.awt.TextField();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        customer_search_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        my_account_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JButton();
        create_offer_btn = new javax.swing.JButton();
        view_prod_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        market_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        channel_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ads_input = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        supplier_drg = new javax.swing.JComboBox<>();
        product_drg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        actual_price_input = new javax.swing.JTextField();
        add_prod_btn = new javax.swing.JButton();
        target_price_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prod_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        quantity_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prod_name = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        setMaximumSize(new java.awt.Dimension(680, 800));
        setPreferredSize(new java.awt.Dimension(664, 800));
        setSize(new java.awt.Dimension(680, 800));

        top_search_panel.setBackground(new java.awt.Color(0, 0, 0));
        top_search_panel.setMaximumSize(new java.awt.Dimension(800, 800));
        top_search_panel.setPreferredSize(new java.awt.Dimension(680, 74));
        top_search_panel.setSize(new java.awt.Dimension(680, 74));

        jLabel1.setBackground(new java.awt.Color(255, 203, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 163, 188));
        jLabel1.setText("Hello, "+this.account.getPerson().getName().split(" ")[0]);

        customer_search_input.setText("");
        customer_search_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_search_inputActionPerformed(evt);
            }
        });

        label1.setText("label1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Search");

        customer_search_btn.setText("Search");

        logout_btn.setBackground(new java.awt.Color(204, 204, 204));
        logout_btn.setText("Log out");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        my_account_btn.setBackground(new java.awt.Color(204, 204, 204));
        my_account_btn.setText("My Account");

        javax.swing.GroupLayout top_search_panelLayout = new javax.swing.GroupLayout(top_search_panel);
        top_search_panel.setLayout(top_search_panelLayout);
        top_search_panelLayout.setHorizontalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_search_btn))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(my_account_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        top_search_panelLayout.setVerticalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_search_panelLayout.createSequentialGroup()
                        .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_btn)
                        .addComponent(my_account_btn))
                    .addComponent(customer_search_btn)
                    .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel1.setBackground(new java.awt.Color(236, 234, 234));

        dashboard_btn.setText("Dashboard");
        dashboard_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseClicked(evt);
            }
        });

        create_offer_btn.setText("Order Requests");
        create_offer_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_offer_btnMouseClicked(evt);
            }
        });

        view_prod_btn.setText("View Products");
        view_prod_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_prod_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_offer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_prod_btn)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboard_btn)
                    .addComponent(create_offer_btn)
                    .addComponent(view_prod_btn)))
        );

        submit_btn.setText("Submit");
        submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_btnMouseClicked(evt);
            }
        });
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        clear_btn.setText("Clear");
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });

        jLabel5.setText("Markets");

        jLabel6.setText("Channel");

        ads_input.setColumns(20);
        ads_input.setRows(5);
        jScrollPane2.setViewportView(ads_input);

        jLabel7.setText("Ads");

        supplier_drg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        ArrayList<Supplier> suppliers = this.data.getBusiness().sd.supplier_list;
        for(Supplier supplier:suppliers){
            supplier_drg.addItem(supplier.person.getPersonId());
        }
        supplier_drg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_drgActionPerformed(evt);
            }
        });

        product_drg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        product_drg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_drgActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplier");

        jLabel9.setText("Product");

        jLabel10.setText("Target Price");

        jLabel11.setText("Actual Price");

        add_prod_btn.setText("Add");
        add_prod_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_prod_btnMouseClicked(evt);
            }
        });

        target_price_label.setText("$0");

        prod_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "PID", "Name","SID","Actual Price", "Quantity"
            }
        ));
        DefaultTableModel dtm = (DefaultTableModel) prod_table.getModel();
        dtm.setRowCount(0);
        dtm.fireTableDataChanged();
        jScrollPane1.setViewportView(prod_table);

        jLabel4.setText("Products Added");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel12.setText("Create Solution Bundle");

        jLabel13.setText("Quantity");

        quantity_input.setText(" ");

        jLabel3.setText("Name");

        prod_name.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplier_drg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(market_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(channel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(product_drg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_prod_btn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prod_name, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(target_price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(actual_price_input, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(quantity_input, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(market_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(channel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier_drg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_drg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actual_price_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(target_price_label)
                    .addComponent(quantity_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_prod_btn)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_btn)
                    .addComponent(clear_btn))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customer_search_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_search_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_search_inputActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_btnActionPerformed

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
        dtm.setRowCount(0);
        dtm.fireTableDataChanged();
        this.ads_input.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void submit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_btnMouseClicked
        // TODO add your handling code here:
        int error = 0;
        //add markets
        ArrayList<String> markets = new ArrayList<String>();
        if(this.market_textfield.getText().isBlank()){
            error++;
        }
        else{ 
            markets = Util.wrapSpaces(this.market_textfield.getText().split(","));
        }
        
        //add channels
        ArrayList<String> channels = new ArrayList<String>();
        if(this.channel_textfield.getText().isBlank()){
            error++;
        }
        else{ 
            channels = Util.wrapSpaces(this.channel_textfield.getText().split(","));
        }
        
        //add products product id, product name, supplier id, actual price, quantity
        DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
        ArrayList<String[]> products = new ArrayList<String[]>();
        if(dtm.getRowCount()<1){
            error++;
        }
        else {
            for(int row=0;row<dtm.getRowCount();row++){
                String[] items = new String[5];
                for(int col=0;col<dtm.getColumnCount();col++){  
                    items[col] = String.valueOf(dtm.getValueAt(row, col)); 
                }
                products.add(items);
            } 
        }
        
        if(this.ads_input.getText().isBlank()){
            error++;
        }
        
        if(error>0){
            JOptionPane.showMessageDialog(this.jf, "Please fill all fields.");
        }
        else {
            DataUtil.createSolutionBundleAssignment(this.data, markets, channels, products, (this.ads_input.getText()), this.data.getEmployees().findEmployee(this.account.getPerson().getPersonId()));
            JOptionPane.showMessageDialog(this.jf, "Successed!");
            cleanPanel();
            CreateOfferScene offer = new CreateOfferScene(this.jf, this.data, this.account);
            UiControl.createOffer(this.jf, offer);
        } 

    }//GEN-LAST:event_submit_btnMouseClicked

    private void dashboard_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        MarketingDashboard dashboard = new MarketingDashboard(this.jf, this.data, this.account);
        UiControl.dashboard(this.jf, dashboard);

    }//GEN-LAST:event_dashboard_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        UserLoginJPanel loginUI = new UserLoginJPanel(jf, data);
        UiControl.logout(this.jf, loginUI);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void supplier_drgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_drgActionPerformed
        // TODO add your handling code here:
        updateSupplierDrg();
    }//GEN-LAST:event_supplier_drgActionPerformed

    private void product_drgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_drgActionPerformed
        // TODO add your handling code here:
        this.actual_price_input.setText("");
        this.quantity_input.setText("");
        if (!String.valueOf(this.product_drg.getSelectedItem()).isBlank() && !String.valueOf(this.supplier_drg.getSelectedItem()).isBlank()) {
            
            Product p = this.data.getBusiness().sd.findSupplier(String.valueOf(this.supplier_drg.getSelectedItem())).pc.findProduct(String.valueOf(this.product_drg.getSelectedItem()));
            if(p!=null){
                this.prod_name.setText(p.getDesc());
                this.target_price_label.setText("$"+String.valueOf(p.getTargetPrice()));
            }
            
        }
    }//GEN-LAST:event_product_drgActionPerformed

    private void add_prod_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_prod_btnMouseClicked
        // TODO add your handling code here:
        
        if (!String.valueOf(this.product_drg.getSelectedItem()).isBlank() && 
            !String.valueOf(this.supplier_drg.getSelectedItem()).isBlank() && 
            !this.actual_price_input.getText().trim().isEmpty() && 
            !this.quantity_input.getText().trim().isEmpty() && 
            Integer.parseInt(this.quantity_input.getText().trim())>0) {
            Product p = this.data.getBusiness().sd.findSupplier(String.valueOf(this.supplier_drg.getSelectedItem())).pc.findProduct(String.valueOf(this.product_drg.getSelectedItem()));
            if(p!=null){
                DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
                String[] row = new String[5];
                row[0] = p.getID();
                row[1] = p.getDesc();
                row[2] = String.valueOf(this.supplier_drg.getSelectedItem());
                row[3] = this.actual_price_input.getText().trim();
                row[4] = this.quantity_input.getText().trim(); 
                dtm.addRow(row);
                dtm.fireTableDataChanged();
            }
            
        }
    }//GEN-LAST:event_add_prod_btnMouseClicked

    private void create_offer_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_offer_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        ViewOrderQuestScene requets = new ViewOrderQuestScene(this.jf, this.data, this.account);
        UiControl.OrderRequest(this.jf, requets);
    }//GEN-LAST:event_create_offer_btnMouseClicked

    private void view_prod_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_prod_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        ViewProductScene prod = new ViewProductScene(this.jf, this.data, this.account);
        UiControl.viewProduct(this.jf, prod);
    }//GEN-LAST:event_view_prod_btnMouseClicked
    private void updateSupplierDrg(){
        this.product_drg.removeAllItems();
        if (!String.valueOf(this.supplier_drg.getSelectedItem()).isBlank()) {
            if(String.valueOf(this.supplier_drg.getSelectedItem()).equals("All")){
                for(Supplier supplier:this.data.getBusiness().sd.supplier_list){
                    for (Product p : this.data.getBusiness().sd.findSupplier(supplier.person.getPersonId()).getProducts()) {
                        this.product_drg.addItem(p.getID());
                    }
                }
            }
            else{
                for (Product p : this.data.getBusiness().sd.findSupplier(this.supplier_drg.getSelectedItem().toString()).getProducts()) {
                    this.product_drg.addItem(p.getID());
                }
            }  
        }
    }
    private void updateSelectedTable(javax.swing.JTable table, ArrayList<Order> orders) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0); 
        dtm.fireTableDataChanged();
    }

    private void cleanPanel() {
        this.setVisible(false);
        this.removeAll();
        this.jf.remove(this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actual_price_input;
    private javax.swing.JButton add_prod_btn;
    private javax.swing.JTextArea ads_input;
    private javax.swing.JTextField channel_textfield;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton create_offer_btn;
    private javax.swing.JButton customer_search_btn;
    private java.awt.TextField customer_search_input;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTextField market_textfield;
    private javax.swing.JButton my_account_btn;
    private javax.swing.JLabel prod_name;
    private javax.swing.JTable prod_table;
    private javax.swing.JComboBox<String> product_drg;
    private javax.swing.JTextField quantity_input;
    private javax.swing.JButton submit_btn;
    private javax.swing.JComboBox<String> supplier_drg;
    private javax.swing.JLabel target_price_label;
    private javax.swing.JPanel top_search_panel;
    private javax.swing.JButton view_prod_btn;
    // End of variables declaration//GEN-END:variables
}
