/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.marketingRole;

import userbusiness.UserLogin;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;
import salesmodel.Data.Data;
import salesmodel.utils.DataUtil;
import ui.UserLoginJPanel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import salesmodel.OrderManagement.Order;
import salesmodel.OrderManagement.OrderItem;
import salesmodel.Personnel.EmployeeProfile;
import ui.UiControl;
import userbusiness.Account;

/**
 *
 * @author faye
 */
public class ViewOrderQuestScene extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtUser;
    private JFrame jf;
    private Data data;
    private Account account;
    private JLabel username_label;
    private JLabel serve_customer_label;
    private JLabel activity_label;
    private ArrayList<Order> pending_orders;
    private ArrayList<Order> selected_orders;

    /**
     * Creates new form MarketingDashboard_new
     */
    public ViewOrderQuestScene(JFrame jf, Data data, Account account) {
        setBackground(new Color(0, 128, 128));
        this.jf = jf;
        this.data = data;
        this.account = account;
        pending_orders = DataUtil.getPendingRequest(this.account.getPerson(), null, this.data);
        this.selected_orders = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        top_search_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_search_input = new java.awt.TextField();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        customer_search_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        my_account_btn = new javax.swing.JButton();
        order_request_panel = new javax.swing.JScrollPane();
        pending_order_table = new javax.swing.JTable();
        order_request_table_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JButton();
        create_offer_btn = new javax.swing.JButton();
        view_prod_btn = new javax.swing.JButton();
        add_pending_order_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selected_orders_table = new javax.swing.JTable();
        submit_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total_selected_price = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        setMaximumSize(new java.awt.Dimension(680, 800));
        setPreferredSize(new java.awt.Dimension(664, 800));
        setSize(new java.awt.Dimension(680, 800));

        top_search_panel.setBackground(new java.awt.Color(0, 0, 0));
        top_search_panel.setMaximumSize(new java.awt.Dimension(800, 800));
        top_search_panel.setPreferredSize(new java.awt.Dimension(680, 74));
        top_search_panel.setSize(new java.awt.Dimension(680, 74));

        jLabel1.setBackground(new java.awt.Color(255, 203, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 163, 188));
        jLabel1.setText("Hello, "+this.account.getPerson().getName().split(" ")[0]);

        customer_search_input.setText("");
        customer_search_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_search_inputActionPerformed(evt);
            }
        });

        label1.setText("label1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Search");

        customer_search_btn.setText("Search");

        logout_btn.setBackground(new java.awt.Color(204, 204, 204));
        logout_btn.setText("Log out");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        my_account_btn.setBackground(new java.awt.Color(204, 204, 204));
        my_account_btn.setText("My Account");

        javax.swing.GroupLayout top_search_panelLayout = new javax.swing.GroupLayout(top_search_panel);
        top_search_panel.setLayout(top_search_panelLayout);
        top_search_panelLayout.setHorizontalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_search_btn))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(my_account_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        top_search_panelLayout.setVerticalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_search_panelLayout.createSequentialGroup()
                        .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_btn)
                        .addComponent(my_account_btn))
                    .addComponent(customer_search_btn)
                    .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        DefaultTableModel dtm = new DefaultTableModel(0, 0);

        String[] header = new String[]{"Customer", "Market", "Channel", "Total Price"};
        dtm.setColumnIdentifiers(header);

        for(Order order : this.pending_orders){
            String[] row = new String[4];
            row[0] = order.getCustomer().getName();
            row[1] = String.join(",", order.getBundleAssignment().getMarketAssignMent().getMarket().getCharacters());
            row[2] = order.getBundleAssignment().getMarketAssignMent().getChannel().getType();
            row[3] = String.valueOf(order.getOrderTotal());
            dtm.addRow(row);
        }
        pending_order_table.setModel(dtm);
        order_request_panel.setViewportView(pending_order_table);

        order_request_table_title.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        order_request_table_title.setText("Pending Orders' Requests");

        jPanel1.setBackground(new java.awt.Color(236, 234, 234));

        dashboard_btn.setText("Dashboard");
        dashboard_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseClicked(evt);
            }
        });

        create_offer_btn.setText("Create Offers");
        create_offer_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_offer_btnMouseClicked(evt);
            }
        });

        view_prod_btn.setText("View Products");
        view_prod_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_prod_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_offer_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_prod_btn)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboard_btn)
                    .addComponent(create_offer_btn)
                    .addComponent(view_prod_btn)))
        );

        add_pending_order_btn.setText("Add");
        add_pending_order_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_pending_order_btnMouseClicked(evt);
            }
        });

        dtm = new DefaultTableModel(0, 0);
        header = new String[]{"Product", "Supplier", "Quantity", "Total Performance"};
        dtm.setColumnIdentifiers(header);
        selected_orders_table.setModel(dtm);
        jScrollPane1.setViewportView(selected_orders_table);

        submit_btn.setText("Submit");
        submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_btnMouseClicked(evt);
            }
        });
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Cancel");
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Total Price:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel4.setText("Selected Orders' Details");

        total_selected_price.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        total_selected_price.setText("$0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit_btn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(95, 95, 95)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(total_selected_price))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(add_pending_order_btn)
                            .addComponent(order_request_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                            .addComponent(order_request_table_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(order_request_table_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(order_request_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_pending_order_btn)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(total_selected_price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_btn)
                    .addComponent(cancel_btn))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customer_search_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_search_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_search_inputActionPerformed

    private void add_pending_order_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_pending_order_btnMouseClicked
        // TODO add your handling code here:
        int selected_row = pending_order_table.getSelectedRow();
        if (selected_row >= 0) {
            this.selected_orders.add(this.pending_orders.get(selected_row));
            this.pending_orders.remove(selected_row);
            //update selected table's rows
            updateSelectedTable(this.selected_orders_table, this.selected_orders);
            updatePendingTable(this.pending_order_table, this.pending_orders);
            updateTotalPrice();
        }


    }//GEN-LAST:event_add_pending_order_btnMouseClicked

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_btnActionPerformed

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        // TODO add your handling code here:
        this.selected_orders.clear();
        this.pending_orders = DataUtil.getPendingRequest(this.account.getPerson(), null, this.data);
        updateSelectedTable(this.selected_orders_table, this.selected_orders);
        updatePendingTable(this.pending_order_table, this.pending_orders);
        updateTotalPrice();
    }//GEN-LAST:event_cancel_btnMouseClicked

    private void submit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_btnMouseClicked
        // TODO add your handling code here:
        if(this.selected_orders.size()>0){
          
            for (Order order : this.selected_orders) {
                order.setStatus("approved");
            }
            this.selected_orders.clear();
            updateSelectedTable(this.selected_orders_table, this.selected_orders);
            updateTotalPrice();
            JOptionPane.showMessageDialog(this.jf, "Successed!"); 
        }
        else {
            JOptionPane.showMessageDialog(this.jf, "Please select at least an order."); 
        }
        
    }//GEN-LAST:event_submit_btnMouseClicked

    private void dashboard_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        MarketingDashboard dashboard = new MarketingDashboard(this.jf, this.data, this.account);
        UiControl.dashboard(this.jf, dashboard);
        
    }//GEN-LAST:event_dashboard_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        UserLoginJPanel loginUI = new UserLoginJPanel(jf, data);
        UiControl.logout(this.jf, loginUI);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void create_offer_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_offer_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CreateOfferScene offer = new CreateOfferScene(this.jf, this.data, this.account);
        UiControl.createOffer(this.jf, offer);
    }//GEN-LAST:event_create_offer_btnMouseClicked

    private void view_prod_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_prod_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        ViewProductScene prod = new ViewProductScene(this.jf, this.data, this.account);
        UiControl.viewProduct(this.jf, prod);
    }//GEN-LAST:event_view_prod_btnMouseClicked

    private void updateSelectedTable(javax.swing.JTable table, ArrayList<Order> orders) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        for (Order order : orders) {
            for (OrderItem item : order.getOrderItems()) {
                String[] row = new String[4];
                row[0] = item.getProduct().getDesc();
                row[1] = item.getProduct().getSupplier().person.getPersonId();
                row[2] = String.valueOf(item.getQuantity());
                row[3] = String.valueOf(item.calculatePricePerformance() * item.getQuantity());
                dtm.addRow(row);
            }
        }
        dtm.fireTableDataChanged();
    }

    private void updatePendingTable(javax.swing.JTable table, ArrayList<Order> orders) {

        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0); 
        for (Order order : orders) {
            String[] row = new String[4];
            row[0] = order.getCustomer().getName();
            row[1] = String.join(",", order.getBundleAssignment().getMarketAssignMent().getMarket().getCharacters());
            row[2] = order.getBundleAssignment().getMarketAssignMent().getChannel().getType();
            row[3] = String.valueOf(order.getOrderTotal());
            dtm.addRow(row);
        }
        dtm.fireTableDataChanged();
    }

    private void updateTotalPrice() {
        int total = 0;
        for (Order order : this.selected_orders) {
            total += order.getOrderTotal();
        }
        this.total_selected_price.setText("$" + String.valueOf(total));
    }
    
    
    private void cleanPanel(){ 
        this.setVisible(false);
        this.removeAll();
        this.jf.remove(this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_pending_order_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton create_offer_btn;
    private javax.swing.JButton customer_search_btn;
    private java.awt.TextField customer_search_input;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton my_account_btn;
    private javax.swing.JScrollPane order_request_panel;
    private javax.swing.JLabel order_request_table_title;
    private javax.swing.JTable pending_order_table;
    private javax.swing.JTable selected_orders_table;
    private javax.swing.JButton submit_btn;
    private javax.swing.JPanel top_search_panel;
    private javax.swing.JLabel total_selected_price;
    private javax.swing.JButton view_prod_btn;
    // End of variables declaration//GEN-END:variables
}
