/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.marketingRole;

import userbusiness.UserLogin;
import javax.swing.GroupLayout.Alignment;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingUtilities;
import salesmodel.Data.Data;
import salesmodel.utils.DataUtil;
import salesmodel.utils.Util;
import ui.UserLoginJPanel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import salesmodel.OrderManagement.Order;
import salesmodel.OrderManagement.OrderItem;
import salesmodel.Personnel.EmployeeProfile;
import salesmodel.ProductManagement.Product;
import salesmodel.SupplierManagement.Supplier;
import ui.UiControl;
import userbusiness.Account;

/**
 *
 * @author faye
 */
public class ViewProductScene extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtUser;
    private JFrame jf;
    private Data data;
    private Account account;
    private JLabel username_label;
    private JLabel serve_customer_label;
    private JLabel activity_label; 
     

    /**
     * Creates new form MarketingDashboard_new
     */
    public ViewProductScene(JFrame jf, Data data, Account account) {
        setBackground(new Color(0, 128, 128));
        this.jf = jf;
        this.data = data;
        this.account = account; 
        initComponents();
        updateSupplierDrg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        top_search_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_search_input = new java.awt.TextField();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        customer_search_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        my_account_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JButton();
        create_offer_btn = new javax.swing.JButton();
        create_offer_btn1 = new javax.swing.JButton();
        supplier_drg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prod_table = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        setMaximumSize(new java.awt.Dimension(680, 800));
        setPreferredSize(new java.awt.Dimension(664, 800));
        setSize(new java.awt.Dimension(680, 800));

        top_search_panel.setBackground(new java.awt.Color(0, 0, 0));
        top_search_panel.setMaximumSize(new java.awt.Dimension(800, 800));
        top_search_panel.setPreferredSize(new java.awt.Dimension(680, 74));
        top_search_panel.setSize(new java.awt.Dimension(680, 74));

        jLabel1.setBackground(new java.awt.Color(255, 203, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 163, 188));
        jLabel1.setText("Hello, "+this.account.getPerson().getName().split(" ")[0]);

        customer_search_input.setText("");
        customer_search_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_search_inputActionPerformed(evt);
            }
        });

        label1.setText("label1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Search");

        customer_search_btn.setText("Search");

        logout_btn.setBackground(new java.awt.Color(204, 204, 204));
        logout_btn.setText("Log out");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        my_account_btn.setBackground(new java.awt.Color(204, 204, 204));
        my_account_btn.setText("My Account");

        javax.swing.GroupLayout top_search_panelLayout = new javax.swing.GroupLayout(top_search_panel);
        top_search_panel.setLayout(top_search_panelLayout);
        top_search_panelLayout.setHorizontalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_search_btn))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(my_account_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        top_search_panelLayout.setVerticalGroup(
            top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_search_panelLayout.createSequentialGroup()
                        .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)))
                .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_btn)
                        .addComponent(my_account_btn))
                    .addComponent(customer_search_btn)
                    .addComponent(customer_search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel1.setBackground(new java.awt.Color(236, 234, 234));

        dashboard_btn.setText("Dashboard");
        dashboard_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseClicked(evt);
            }
        });

        create_offer_btn.setText("Order Requests");
        create_offer_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_offer_btnMouseClicked(evt);
            }
        });

        create_offer_btn1.setText("Create Offers");
        create_offer_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_offer_btn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_offer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_offer_btn1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_offer_btn1)
                    .addComponent(create_offer_btn)
                    .addComponent(dashboard_btn))
                .addContainerGap())
        );

        supplier_drg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        ArrayList<Supplier> suppliers = this.data.getBusiness().sd.supplier_list;
        for(Supplier supplier:suppliers){
            supplier_drg.addItem(supplier.person.getPersonId());
        }
        supplier_drg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_drgActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplier");

        DefaultTableModel dtm = (DefaultTableModel) prod_table.getModel();
        String header[] = new String [] {"PID", "Name","Floor Price", "Ceiling Price","Target Price"};
        dtm.setColumnIdentifiers(header);
        dtm.setRowCount(0);
        // add header in table model
        prod_table.setModel(dtm);
        jScrollPane1.setViewportView(prod_table);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel12.setText("Manage Products");

        jButton1.setText("+");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(supplier_drg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(update_btn)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier_drg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customer_search_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_search_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_search_inputActionPerformed

    private void dashboard_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        MarketingDashboard dashboard = new MarketingDashboard(this.jf, this.data, this.account);
        UiControl.dashboard(this.jf, dashboard);

    }//GEN-LAST:event_dashboard_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        UserLoginJPanel loginUI = new UserLoginJPanel(jf, data);
        UiControl.logout(this.jf, loginUI);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void supplier_drgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_drgActionPerformed
        // TODO add your handling code here:
        updateSupplierDrg();
    }//GEN-LAST:event_supplier_drgActionPerformed

    private void create_offer_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_offer_btnMouseClicked
        // TODO add your handling code here:
        cleanPanel();
        ViewOrderQuestScene requets = new ViewOrderQuestScene(this.jf, this.data, this.account);
        UiControl.OrderRequest(this.jf, requets);
    }//GEN-LAST:event_create_offer_btnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
        dtm.addRow(new String[]{"","","0","0","0"});
        dtm.fireTableDataChanged();
    }//GEN-LAST:event_jButton1MouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        if(!String.valueOf(this.supplier_drg.getSelectedItem()).trim().isEmpty()){
            ArrayList<String[]> products = new ArrayList<String[]>();
           
            DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
            int error = 0;
            for(int row=0;row<dtm.getRowCount();row++){
                String[] r = new String[5];
                
                if(!String.valueOf(dtm.getValueAt(row, 0)).trim().isEmpty()){
                    r[0] = String.valueOf(dtm.getValueAt(row, 0)).trim();
                }
                else{
                    error++;
                }
                if(!String.valueOf(dtm.getValueAt(row, 1)).trim().isEmpty()){
                    r[1] = String.valueOf(dtm.getValueAt(row, 1)).trim();
                }
                if(Util.isInteger(String.valueOf(dtm.getValueAt(row, 2)))){
                    r[2] =  String.valueOf(dtm.getValueAt(row, 2));
                }
                else{
                    error++;
                }
                if(Util.isInteger(String.valueOf(dtm.getValueAt(row, 3)))){
                    r[3] =  String.valueOf(dtm.getValueAt(row, 3));
                }
                else{
                    error++;
                }
                if(Util.isInteger(String.valueOf(dtm.getValueAt(row, 4)))){
                    r[4] = String.valueOf(dtm.getValueAt(row, 4));
                }
                else{
                    error++;
                }
                if(error<1){ 
                    products.add(r);
                }
                else{
                    break;
                }
            }
            if(error<1){
                DataUtil.updateProduct(this.data, products, String.valueOf(this.supplier_drg.getSelectedItem()).trim());
                JOptionPane.showMessageDialog(this.jf, "Successed!");
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_update_btnMouseClicked

    private void create_offer_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_offer_btn1MouseClicked
        // TODO add your handling code here:
        cleanPanel();
        CreateOfferScene offer = new CreateOfferScene(this.jf, this.data, this.account);
        UiControl.createOffer(this.jf, offer);
    }//GEN-LAST:event_create_offer_btn1MouseClicked
    private void updateSupplierDrg(){
        DefaultTableModel dtm = (DefaultTableModel) this.prod_table.getModel();
        dtm.setRowCount(0);
        if (!String.valueOf(this.supplier_drg.getSelectedItem()).isBlank()) {
            for (Product p : this.data.getBusiness().sd.findSupplier(this.supplier_drg.getSelectedItem().toString()).getProducts()) {
                String[] row = new String[]{p.getID(), p.getDesc(), String.valueOf(p.getFloor()), String.valueOf(p.getCeil()), String.valueOf(p.getTargetPrice())};
                dtm.addRow(row);
            }  
        }
        dtm.fireTableDataChanged();
    }
    private void updateSelectedTable(javax.swing.JTable table, ArrayList<Order> orders) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0); 
        dtm.fireTableDataChanged();
    }

    private void cleanPanel() {
        this.setVisible(false);
        this.removeAll();
        this.jf.remove(this);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_offer_btn;
    private javax.swing.JButton create_offer_btn1;
    private javax.swing.JButton customer_search_btn;
    private java.awt.TextField customer_search_input;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton my_account_btn;
    private javax.swing.JTable prod_table;
    private javax.swing.JComboBox<String> supplier_drg;
    private javax.swing.JPanel top_search_panel;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
